version: "2.4"
services:
    service:
        build:
            context: .
            dockerfile: Dockerfile
        image: nickchiang/skl_ner_service
        container_name: sklNerService
        privileged: true
        restart: always
        # runtime: nvidia
        environment:
          #- NVIDIA_VISIBLE_DEVICES=all
          - port=8080
        volumes:
          - ".:/app/"
        cap_add:
          - SYS_ADMIN
        ports:
          - "8080:8080"
        networks:
          - my_net

networks:
    my_net:
        driver: bridge
